### ISSUE TITLE
Incompatible with buildcraft-compat

### ISSUE THREAD

**Issue by LemADEC** [thomas15v/DeviantFix#4]
When buildcraft-compat mod is installed along side with buildcraft itself, DeviantFix will patch the wrong mod buildcraft-compat, causing numerous crashes behind.
Same issue happens if a mod is disabled by renaming it: if I have "Railcraft-1.7.10-fixed.jar" and "Railcraft-1.7.10.jar-original", then the one that'll be patched is "Railcraft-1.7.10.jar-original".

**Comment by thomas15v** [comment]
Hmmmm that could indeed be an issue. Look the patcher works as followed:
https://github.com/TheDeviantNetwork/DeviantFix/blob/master/src/main/java/com/thedeviantnetwork/deviantfix/DeviantFixCoreMod.java#L16.

When it finds a jar with `buildcraft*` it will patch the FIRST one it finds. I would recommend renaming buildcraft-compat.jar to compat-buildcraft.jar. Same counts for other mods.
